### ISSUE TITLE
Generate request id if not present

### ISSUE THREAD

**Issue by mattolson** [remind101/request_id#14]
In https://github.com/remind101/request_id/pull/7 functionality was added to generate a request id if it doesn't exist already (based on a configuration value). However, in https://github.com/remind101/request_id/pull/13 it appears that this functionality was unintentionally removed. Or at least, if is was intentional, it wasn't mentioned in the PR comments, and the configuration values are still in master. 

I would like to use this functionality. If I filed a PR to restore it, would you merge, or is there another reason it was removed?

**Comment by ejholmes** [comment]
Ah, yeah that was probably unintentional. We do the generation in our routing tier, but it's still pretty nice to have in development. If you wanna give it a go we'll accept a PR :)
