### ISSUE TITLE
Is this project maintained?

### ISSUE THREAD

**Issue by srt32** [remind101/request_id#19]
Hi `request_id` folks,

We're interested in using this library but it appears there has been no work on `master` since 9/2015.

Is this library actively maintained? Would y'all accept new maintainers if we found folks willing to adopt it?

Thanks for this gem!

**Comment by gingerlime** [comment]
I saw some forks, but they're fragmented... It's definitely something useful and I'm sure people will use and be happy to maintain and contribute to. How can we collectively agree on a successor if the maintainer is unresponsive?

**Comment by rex-remind101** [comment]
we no longer maintain this. @gingerlime or @srt32 let me know if you wish to take over. we'll add a deprecated banner on our readme and a link out to your fork.
