### ISSUE TITLE
Sidekiq 5.0 support

### ISSUE THREAD

**Issue by srt32** [remind101/request_id#22]
There were [breaking changes](https://github.com/mperham/sidekiq/blob/master/Changes.md#500) as of `sidekiq` `5.0` that affect `request_id`. Namely, some class renaming around logging:

> Sidekiq::Middleware::Server::Logging -> Sidekiq::JobLogger

That removed class appears to be used in https://github.com/remind101/request_id/blob/dfa414e8542a682187b3742b875cb605af2abe15/lib/sidekiq/middleware/server/request_id.rb#L10 and https://github.com/remind101/request_id/blob/dfa414e8542a682187b3742b875cb605af2abe15/spec/support/sidekiq.rb#L13

Errors look something like:

```
superclass must be a Class (Module given)
```

Has anyone had luck attempting an update? I will do some tests and report back.

**Comment by bluurn** [comment]
Hey @srt32! Have you succeeded in adding the Sidekiq 5.0 support or shall I try to fix it?

**Comment by srt32** [comment]
@bluurn I am not working on this issue. Please feel free to work on it!

**Comment by bluurn** [comment]
@srt32 Done :)
